name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-24.04, macos-14]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - run: make
    - run: make dist
    - run: make test

